version: "3.7"
services:
  web:
    build: ./web
    command: yarn start
    restart: on-failure
    environment:
      REACT_APP_LOCAL: local
    volumes:
      - ./web:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
  next:
    build: ./next
    command: yarn dev
    restart: on-failure
    environment:
      REACT_APP_LOCAL: local
    volumes:
      - ./next:/usr/src/app
    ports:
      - "4000:3000"
    depends_on:
      - api
  api:
    build:
      context: ./api
      target: builder
    command: yarn start:dev
    restart: on-failure
    environment:
      POSTGRES_HOST: db 
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgresdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: onlyfordev
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules # prevent node_modules from being overridden
    ports:
      - "8000:3000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: onlyfordev
    volumes:
      - ./data/sql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
